import type {
  Course,
  Unit,
  Lesson,
  Practical,
  PerformanceAssessment,
} from './types';

// Courses
export const MOCK_COURSES: Course[] = [
  {
    id: 'course-001',
    title: 'Trumpet Fundamentals',
    description: 'Master the basics of trumpet playing, including embouchure, breathing, and tone production.',
    code: 'GAFMS-TRP-101',
    instructorId: 'inst-001',
    units: ['unit-001', 'unit-002', 'unit-003'],
    createdAt: '2024-01-15',
    startDate: '2024-02-01',
    endDate: '2024-04-30',
    status: 'active',
  },
  {
    id: 'course-002',
    title: 'Music Theory I',
    description: 'Introduction to music theory covering scales, intervals, chords, and basic harmony.',
    code: 'GAFMS-THY-101',
    instructorId: 'inst-001',
    units: ['unit-004', 'unit-005'],
    createdAt: '2024-01-10',
    startDate: '2024-02-01',
    endDate: '2024-05-31',
    status: 'active',
  },
  {
    id: 'course-003',
    title: 'Percussion Performance',
    description: 'Comprehensive training in percussion instruments including drums, timpani, and mallets.',
    code: 'GAFMS-PRC-201',
    instructorId: 'inst-002',
    units: ['unit-006', 'unit-007'],
    createdAt: '2024-01-20',
    startDate: '2024-02-15',
    endDate: '2024-05-15',
    status: 'active',
  },
  {
    id: 'course-004',
    title: 'Ensemble Conducting',
    description: 'Learn the fundamentals of conducting, score reading, and ensemble management.',
    code: 'GAFMS-CND-301',
    instructorId: 'inst-003',
    units: ['unit-008', 'unit-009'],
    createdAt: '2024-02-01',
    startDate: '2024-03-01',
    endDate: '2024-06-30',
    status: 'active',
  },
  {
    id: 'course-005',
    title: 'Music Composition',
    description: 'Develop skills in musical composition, arrangement, and orchestration.',
    code: 'GAFMS-CMP-401',
    instructorId: 'inst-003',
    units: ['unit-010', 'unit-011'],
    createdAt: '2024-02-05',
    startDate: '2024-03-15',
    endDate: '2024-07-15',
    status: 'active',
  },
];

// Units
export const MOCK_UNITS: Unit[] = [
  {
    id: 'unit-001',
    courseId: 'course-001',
    title: 'Embouchure & Basic Technique',
    description: 'Foundation concepts for proper trumpet playing technique',
    lessons: ['lesson-001', 'lesson-002', 'lesson-003'],
    order: 1,
  },
  {
    id: 'unit-002',
    courseId: 'course-001',
    title: 'Scales & Arpeggios',
    description: 'Building finger dexterity and range',
    lessons: ['lesson-004', 'lesson-005'],
    order: 2,
  },
  {
    id: 'unit-003',
    courseId: 'course-001',
    title: 'Repertoire Performance',
    description: 'Playing trumpet pieces and solos',
    lessons: ['lesson-006', 'lesson-007'],
    order: 3,
  },
  {
    id: 'unit-004',
    courseId: 'course-002',
    title: 'Notes, Scales & Key Signatures',
    description: 'Understanding musical notation and scales',
    lessons: ['lesson-008', 'lesson-009'],
    order: 1,
  },
  {
    id: 'unit-005',
    courseId: 'course-002',
    title: 'Intervals & Chords',
    description: 'Learning harmonic structures',
    lessons: ['lesson-010', 'lesson-011'],
    order: 2,
  },
  {
    id: 'unit-006',
    courseId: 'course-003',
    title: 'Drum Kit Fundamentals',
    description: 'Introduction to drum kit and basic grooves',
    lessons: ['lesson-012', 'lesson-013'],
    order: 1,
  },
  {
    id: 'unit-007',
    courseId: 'course-003',
    title: 'Timpani & Mallets',
    description: 'Advanced percussion techniques',
    lessons: ['lesson-014', 'lesson-015'],
    order: 2,
  },
  {
    id: 'unit-008',
    courseId: 'course-004',
    title: 'Conducting Technique',
    description: 'Baton grip, patterns, and gestures',
    lessons: ['lesson-016', 'lesson-017'],
    order: 1,
  },
  {
    id: 'unit-009',
    courseId: 'course-004',
    title: 'Score Preparation & Interpretation',
    description: 'Analyzing and interpreting musical scores',
    lessons: ['lesson-018', 'lesson-019'],
    order: 2,
  },
  {
    id: 'unit-010',
    courseId: 'course-005',
    title: 'Composition Basics',
    description: 'Creating original musical compositions',
    lessons: ['lesson-020', 'lesson-021'],
    order: 1,
  },
  {
    id: 'unit-011',
    courseId: 'course-005',
    title: 'Orchestration & Arrangement',
    description: 'Arranging music for different ensembles',
    lessons: ['lesson-022', 'lesson-023'],
    order: 2,
  },
];

// Lessons
export const MOCK_LESSONS: Lesson[] = [
  {
    id: 'lesson-001',
    unitId: 'unit-001',
    title: 'Embouchure Formation',
    description: 'How to form proper trumpet embouchure',
    content:
      'The embouchure is the position and use of your lips, facial muscles, and mouth cavity to produce sound. Proper embouchure is essential for trumpet success.',
    resources: ['video-embouchure-basics.mp4', 'diagram-embouchure.pdf'],
    duration: 45,
    order: 1,
  },
  {
    id: 'lesson-002',
    unitId: 'unit-001',
    title: 'Breathing Techniques',
    description: 'Proper breathing for sustained trumpet playing',
    content:
      'Learn diaphragmatic breathing and breath control techniques to support long notes and phrases.',
    resources: ['video-breathing.mp4', 'breathing-exercise.pdf'],
    duration: 40,
    order: 2,
  },
  {
    id: 'lesson-003',
    unitId: 'unit-001',
    title: 'Valve Mechanics',
    description: 'Understanding and operating trumpet valves',
    content:
      'Explore how valves work, proper finger positioning, and coordinating valves with breathing.',
    resources: ['video-valve-mechanics.mp4'],
    duration: 35,
    order: 3,
  },
  {
    id: 'lesson-004',
    unitId: 'unit-002',
    title: 'Major Scales',
    description: 'Playing major scales on trumpet',
    content: 'Master all 12 major scales and their patterns.',
    resources: ['scale-exercises.pdf', 'audio-major-scales.mp3'],
    duration: 50,
    order: 1,
  },
  {
    id: 'lesson-005',
    unitId: 'unit-002',
    title: 'Arpeggios & Patterns',
    description: 'Arpeggio exercises for technical development',
    content:
      'Build finger strength and dexterity through arpeggio exercises.',
    resources: ['arpeggio-workbook.pdf', 'audio-arpeggios.mp3'],
    duration: 45,
    order: 2,
  },
  {
    id: 'lesson-006',
    unitId: 'unit-003',
    title: 'Solo Preparation',
    description: 'Preparing trumpet solos for performance',
    content: 'Learn strategies for preparing and performing trumpet solos.',
    resources: ['solo-repertoire.pdf'],
    duration: 60,
    order: 1,
  },
  {
    id: 'lesson-007',
    unitId: 'unit-003',
    title: 'Performance Practice',
    description: 'Techniques for confident performance',
    content:
      'Stage presence, managing nervousness, and delivering compelling performances.',
    resources: ['performance-guide.pdf'],
    duration: 50,
    order: 2,
  },
  {
    id: 'lesson-008',
    unitId: 'unit-004',
    title: 'The Musical Alphabet & Staff',
    description: 'Reading musical notation',
    content: 'Learn the notes on the staff and proper notation.',
    resources: ['notation-basics.pdf'],
    duration: 40,
    order: 1,
  },
  {
    id: 'lesson-009',
    unitId: 'unit-004',
    title: 'Key Signatures',
    description: 'Understanding key signatures',
    content: 'Learn the circle of fifths and key signature patterns.',
    resources: ['key-signatures.pdf', 'circle-of-fifths.pdf'],
    duration: 45,
    order: 2,
  },
  {
    id: 'lesson-010',
    unitId: 'unit-005',
    title: 'Intervals',
    description: 'Understanding musical intervals',
    content:
      'Learn interval identification and their characteristics in music.',
    resources: ['intervals.pdf', 'audio-intervals.mp3'],
    duration: 50,
    order: 1,
  },
  {
    id: 'lesson-011',
    unitId: 'unit-005',
    title: 'Chord Construction',
    description: 'Building and understanding chords',
    content:
      'Learn triads, seventh chords, and their uses in harmony.',
    resources: ['chords.pdf', 'chord-progressions.mp3'],
    duration: 55,
    order: 2,
  },
  {
    id: 'lesson-012',
    unitId: 'unit-006',
    title: 'Drum Kit Setup',
    description: 'Proper drum kit assembly and tuning',
    content: 'Assembling a drum kit and basic tuning techniques.',
    resources: ['drum-kit-setup.pdf', 'video-tuning.mp4'],
    duration: 40,
    order: 1,
  },
  {
    id: 'lesson-013',
    unitId: 'unit-006',
    title: 'Basic Grooves',
    description: 'Learning fundamental drum grooves',
    content: 'Rock, jazz, and funk groove patterns for beginners.',
    resources: ['grooves.pdf', 'audio-grooves.mp3'],
    duration: 45,
    order: 2,
  },
  {
    id: 'lesson-014',
    unitId: 'unit-007',
    title: 'Timpani Technique',
    description: 'Timpani mallets, grips, and striking',
    content: 'Proper technique for playing timpani in ensembles.',
    resources: ['timpani-technique.pdf'],
    duration: 50,
    order: 1,
  },
  {
    id: 'lesson-015',
    unitId: 'unit-007',
    title: 'Mallets & Strikes',
    description: 'Different mallets and percussion strikes',
    content: 'Mallet selection and striking techniques for various percussion instruments.',
    resources: ['mallets-guide.pdf'],
    duration: 45,
    order: 2,
  },
  {
    id: 'lesson-016',
    unitId: 'unit-008',
    title: 'Baton Grip & Posture',
    description: 'Proper conductor positioning',
    content: 'Learning the correct baton grip and conducting posture.',
    resources: ['conducting-posture.pdf', 'video-baton.mp4'],
    duration: 40,
    order: 1,
  },
  {
    id: 'lesson-017',
    unitId: 'unit-008',
    title: 'Time Patterns',
    description: 'Conducting in different time signatures',
    content:
      'Mastering 2/4, 3/4, 4/4, and other common time signatures.',
    resources: ['time-patterns.pdf', 'video-patterns.mp4'],
    duration: 50,
    order: 2,
  },
  {
    id: 'lesson-018',
    unitId: 'unit-009',
    title: 'Score Reading for Conductors',
    description: 'Analyzing orchestral scores',
    content:
      'Learning to read full orchestral scores and understand all instruments.',
    resources: ['score-analysis.pdf'],
    duration: 60,
    order: 1,
  },
  {
    id: 'lesson-019',
    unitId: 'unit-009',
    title: 'Interpretation & Expression',
    description: 'Musical interpretation and gestures',
    content: 'Conveying musical expression through conducting gestures.',
    resources: ['interpretation-guide.pdf'],
    duration: 50,
    order: 2,
  },
  {
    id: 'lesson-020',
    unitId: 'unit-010',
    title: 'Melodic Composition',
    description: 'Creating original melodies',
    content: 'Principles of melody writing and composition.',
    resources: ['melody-composition.pdf'],
    duration: 60,
    order: 1,
  },
  {
    id: 'lesson-021',
    unitId: 'unit-010',
    title: 'Harmonic Development',
    description: 'Building harmonic progressions',
    content: 'Creating supporting harmonies and chord progressions.',
    resources: ['harmony-guide.pdf'],
    duration: 60,
    order: 2,
  },
  {
    id: 'lesson-022',
    unitId: 'unit-011',
    title: 'Orchestration Basics',
    description: 'Writing for different instrument families',
    content: 'Understanding instrument ranges and orchestral scoring.',
    resources: ['orchestration.pdf'],
    duration: 70,
    order: 1,
  },
  {
    id: 'lesson-023',
    unitId: 'unit-011',
    title: 'Arrangement Techniques',
    description: 'Arranging existing music',
    content: 'Adapting music for different ensembles and skill levels.',
    resources: ['arrangement-techniques.pdf'],
    duration: 65,
    order: 2,
  },
];

// Practicals
export const MOCK_PRACTICALS: Practical[] = [
  {
    id: 'practical-001',
    lessonId: 'lesson-001',
    title: 'Embouchure Formation Practical',
    description: 'Record yourself forming and testing different embouchure positions',
    requirements: [
      'Video recording (MP4 or MOV)',
      'Minimum 2 minutes duration',
      'Clear view of mouth and embouchure position',
    ],
    dueDate: '2024-02-28',
    submissions: ['submission-001', 'submission-002', 'submission-003'],
    maxAttempts: 3,
  },
  {
    id: 'practical-002',
    lessonId: 'lesson-004',
    title: 'Major Scales Performance',
    description: 'Perform all 12 major scales on your instrument',
    requirements: [
      'Audio recording (MP3 or WAV)',
      'All 12 major scales required',
      'Steady tempo, clear articulation',
    ],
    dueDate: '2024-03-15',
    submissions: ['submission-004', 'submission-005'],
    maxAttempts: 2,
  },
  {
    id: 'practical-003',
    lessonId: 'lesson-006',
    title: 'Solo Performance',
    description: 'Perform a prepared trumpet solo',
    requirements: [
      'Video recording',
      'Professional presentation',
      'Complete solo performance',
      'Maximum 5 minutes',
    ],
    dueDate: '2024-04-10',
    submissions: ['submission-006'],
    maxAttempts: 2,
  },
  {
    id: 'practical-004',
    lessonId: 'lesson-012',
    title: 'Drum Kit Groove Performance',
    description: 'Perform a basic and an intermediate drum groove',
    requirements: [
      'Video recording',
      'At least 2 different grooves',
      'Clear audio of drums',
      '2-3 minutes total',
    ],
    dueDate: '2024-03-20',
    submissions: ['submission-007', 'submission-008'],
    maxAttempts: 3,
  },
];

// Mock AI Assessment Results
export const MOCK_ASSESSMENTS: PerformanceAssessment[] = [
  {
    id: 'assessment-001',
    submissionId: 'submission-001',
    technicalAccuracy: 82,
    musicality: 78,
    rhythm: 85,
    tonalQuality: 80,
    overallScore: 81,
    feedback:
      'Good embouchure formation with consistent tone production. Work on achieving more evenness across the register.',
    generatedAt: '2024-02-28T14:30:00Z',
    improvementSuggestions: [
      'Practice long tones to improve tone consistency',
      'Focus on upper register stability',
      'Work on dynamic control',
    ],
  },
  {
    id: 'assessment-002',
    submissionId: 'submission-002',
    technicalAccuracy: 88,
    musicality: 82,
    rhythm: 90,
    tonalQuality: 85,
    overallScore: 86,
    feedback:
      'Excellent technical execution and clear improvement from previous submission. Embouchure is well-formed and stable.',
    generatedAt: '2024-02-28T15:45:00Z',
    improvementSuggestions: [
      'Continue developing tonal consistency',
      'Explore more expressive articulation',
      'Work on crescendos and diminuendos',
    ],
  },
  {
    id: 'assessment-003',
    submissionId: 'submission-003',
    technicalAccuracy: 75,
    musicality: 72,
    rhythm: 78,
    tonalQuality: 76,
    overallScore: 75,
    feedback:
      'Solid effort with generally good embouchure formation. Some intonation issues present. Continue consistent practice.',
    generatedAt: '2024-02-29T10:15:00Z',
    improvementSuggestions: [
      'Practice with tuner to improve intonation',
      'Work on breath support consistency',
      'Record and listen back regularly',
    ],
  },
  {
    id: 'assessment-004',
    submissionId: 'submission-004',
    technicalAccuracy: 91,
    musicality: 87,
    rhythm: 93,
    tonalQuality: 89,
    overallScore: 90,
    feedback:
      'Impressive scale work with excellent articulation and rhythmic precision. Clearly demonstrates technical mastery.',
    generatedAt: '2024-03-15T11:20:00Z',
    improvementSuggestions: [
      'Explore expressive variations on scales',
      'Work on smooth legato passages',
      'Develop musical interpretation beyond technical execution',
    ],
  },
];

// Get all mock data organized by entity
export const mockDatabase = {
  courses: MOCK_COURSES,
  units: MOCK_UNITS,
  lessons: MOCK_LESSONS,
  practicals: MOCK_PRACTICALS,
  assessments: MOCK_ASSESSMENTS,
};

// Helper to get related data
export function getCourseData(courseId: string) {
  const course = MOCK_COURSES.find(c => c.id === courseId);
  if (!course) return null;

  const units = MOCK_UNITS.filter(u => course.units.includes(u.id));
  const lessons = MOCK_LESSONS.filter(l =>
    units.some(u => u.lessons.includes(l.id)),
  );
  const practicals = MOCK_PRACTICALS.filter(p =>
    lessons.some(l => l.id === p.lessonId),
  );

  return { course, units, lessons, practicals };
}
